### ISSUE TITLE
Fix TPCH failing benchmark

### ISSUE THREAD

**Issue by okoshovetc** [tarantool/bench-run#15]
Right now tarantool's source code is being patched to pass through some of TPCH queries. This resulted in failure on one [day](https://gitlab.com/tarantool/tarantool/-/jobs/915520395). This patching has to stop.

**Comment by tsafin** [comment]
Waiting till https://github.com/tarantool/tarantool/issues/4898 
We will return to proper datetime support in SQL the next quarter. Once datetime will be landed - we will stop patching, unless then those patches are inevitable.

**Comment by okoshovetc** [comment]
There are still queries that are working properly, so I guess we'd just remove the patching, and at somepoint more queries would work in TPCH.

**Comment by tsafin** [comment]
> There are still queries that are working properly, so I guess we'd just remove the patching, and at somepoint more queries would work in TPCH.

Please don't - we specifically were interested in Q13, Q17 and Q20 as biggest outliers. Without them TPC-H benchmarking making no sense for us.
